### ISSUE TITLE
Please add a screen shot and rename it

### ISSUE THREAD

**Issue by unixorn** [thaffenden/wynwyn.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, please rename the theme so that I can add it to the list - **oh-my-zsh-theme** is a bit generic :-)

Thanks!

**Comment by thaffenden** [comment]
Thanks for your interest!
I've been thinking about doing both of those things for a while but haven't got round to it.

I've renamed it now, and will add some screenshots tommorrow.

**Comment by thaffenden** [comment]
@unixorn all done.
Let me know if you'd like anything else updated, and by all means add it to the `awesome-zsh-plugins` list!

**Comment by unixorn** [comment]
Added it to the list. Thanks for the update!
